# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/jingtao910429/2BossSpecs.git'

target 'TBInteractiveProtocol' do
    use_frameworks!
    pod 'TBWebViewJavascriptBridge'
    pod 'NJKWebViewProgress'
    pod 'ObjectMapper', '~> 2.0.0'
#    pod 'RongCloudIMLibrary', '~> 0.0.7'
#    pod 'TBInteractiveProtocol', '~> 0.0.1'
end
